-- public.banners definition

-- Drop table

-- DROP TABLE public.banners;

CREATE TABLE public.banners (
	id int8 NOT NULL,
	banner_image varchar(255) NULL,
	banner_name varchar(255) NULL,
	created_at timestamp(6) NULL,
	description varchar(255) NULL,
	updated_at timestamp(6) NULL,
	CONSTRAINT banners_pkey PRIMARY KEY (id)
);


-- public.services definition

-- Drop table

-- DROP TABLE public.services;

CREATE TABLE public.services (
	id int8 NOT NULL,
	code varchar(255) NULL,
	created_at timestamp(6) NULL,
	description varchar(255) NULL,
	icon varchar(255) NULL,
	"name" varchar(255) NULL,
	tarrif numeric(38, 2) NULL,
	updated_at timestamp(6) NULL,
	CONSTRAINT services_pkey PRIMARY KEY (id),
	CONSTRAINT uk3ff0vue74scb6a5dbic1yj2ip UNIQUE (code)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	email varchar(255) NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	"password" varchar(255) NULL,
	profile_image text NULL,
	updated_at timestamp(6) NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- public.transactions definition

-- Drop table

-- DROP TABLE public.transactions;

CREATE TABLE public.transactions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric(38, 2) NULL,
	created_at timestamp(6) NULL,
	description varchar(255) NULL,
	invoice_number varchar(255) NULL,
	transaction_type varchar(255) NULL,
	updated_at timestamp(6) NULL,
	user_id int8 NOT NULL,
	CONSTRAINT transactions_pkey PRIMARY KEY (id),
	CONSTRAINT fkqwv7rmvc8va8rep7piikrojds FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.user_balance definition

-- Drop table

-- DROP TABLE public.user_balance;

CREATE TABLE public.user_balance (
	user_id int8 NOT NULL,
	balance numeric(38, 2) NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	CONSTRAINT user_balance_pkey PRIMARY KEY (user_id),
	CONSTRAINT fkdc2arkxowqwkfyhymlokgj7k0 FOREIGN KEY (user_id) REFERENCES public.users(id)
);