spring.application.name=simsppob

## PostgreSQL
spring.datasource.url=${DATABASE_PUBLIC_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.database=POSTGRESQL

railway.s3.endpointurl=${AWS_ENDPOINT_URL}
railway.s3.bucketname=${AWS_S3_BUCKET_NAME}
railway.s3.region=${AWS_DEFAULT_REGION}
railway.s3.id-key=${AWS_ACCESS_KEY_ID}
railway.s3.secret-key=${AWS_SECRET_ACCESS_KEY}
