spring.application.name=simsppob

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=mkyong
spring.datasource.password=password
spring.jpa.database=POSTGRESQL

